version: '3'
networks:
  db:
  web:
services:
  db:
    image: mongo:3.4.10
    restart: always
    volumes:
      - ./data:/usr/src/app/data/db
    networks:
      - db
  backend:
    image: node:carbon
    restart: always
    volumes:
      - ./src:/usr/src/app/src
    build: .
    ports:
      - 5002:5000
    networks:
      - web
      - db
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DB_SERVER=db
      - DB_NAME=bartholomew
      - PORT=5000
